name: audiocutter_example
description: Demonstrates how to use the audiocutter plugin.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.13.1
  path_provider: ^1.1.0
  audiocutter:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - bensound-sunny.mp3
