name: audiocutter
description: A plugin to cut audio files. Supports iOS and Android.
version: 0.0.7
author: thejacer87 <jacebennest87@gmail.com>
homepage: https://gitlab.com/thejacer87/audiocutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ffmpeg: ^0.2.7
  path_provider: ^1.1.2

flutter:
  plugin:
    androidPackage: com.thejacer87.audiocutter
    pluginClass: AudiocutterPlugin
